### ISSUE TITLE
Push Service not working on Humhub 1.15

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6644]
After installing [Push Updates / Push Service](https://docs.humhub.org/docs/admin/push-updates/#pushservice-installation)

Humhub doesn't work anymore (a 3rd argument is missing in `Firebase\JWT\JWT::encode()`):

```
ArgumentCountError: Too few arguments to function
Firebase\JWT\JWT::encode(), 2 passed in
/var/www/humhub/protected/humhub/modules/live/driver/Push.php
on line 116 and at least 3 expected in
/var/www/humhub/protected/vendor/firebase/php-jwt/src/JWT.php:193
Stack trace:
#0
/var/www/humhub/protected/humhub/modules/live/driver/Push.php(116):
Firebase\JWT\JWT::encode(Array, 'eyJhbGciOiJIUzI...')
#1
/var/www/humhub/protected/humhub/modules/live/driver/Push.php(92):
humhub\modules\live\driver\Push->generateJwtAuthorization()
#2
/var/www/humhub/protected/humhub/widgets/CoreJsConfig.php(43):
humhub\modules\live\driver\Push->getJsConfig()
#3
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(146):
humhub\widgets\CoreJsConfig->run()
#4
/var/www/humhub/protected/humhub/modules/ui/view/components/View.php(491):
yii\base\Widget::widget()
#5
/var/www/humhub/protected/modules/clean-theme/themes/clean-base/views/humhub/layouts/main.php(65):
humhub\modules\ui\view\components\View->endBody()
#6
/var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(347):
require('/home/clients/0...')
#7
/var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257):
yii\base\View->renderPhpFile('/home/clients/0...', Array)
#8
/var/www/humhub/protected/humhub/components/Controller.php(155):
yii\base\View->renderFile('/home/clients/0...', Array,
Object(humhub\modules\admin\controllers\GroupController))
#9
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(408):
humhub\components\Controller->renderContent
```

PS: links on https://www.npmjs.com/package/humhub-pushservice for doc and repository are broken.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15
| PHP version      | 8.2

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6646.
